id: PE038BD40
initial_creation_type: input
source_metadata:
  title: Ethical Guidelines
  language: fr
  description: 'The following texts are currently available as part of our Ethical
    Guidelines series:'
  volume:
    7aaf4916a40344619ba8097284642f9d:
      title: A Powerful Pith Instruction to Abstain from Tobacco, the Tenacious Demon
        Plaguing People of Degenerate Times
      parent: Abstention
    46df4c70d55b441eb04684182d6f07f1:
      title: Song of Advice for Giving Up Meat Eating
      parent: Abstention
    04a808c08ca54330884a1d15f8e758a7:
      title: The Mirror Clearly Showing What to Adopt and Abandon
      parent: Behavioural Guidelines
    c666769f15454e12b3105bcd4cc656fe:
      title: Drodung Monastery Guidelines
      parent: Behavioural Guidelines
    826c299a72594416a5fa9ef6c153c21e:
      title: 'The Pellucid Mirror: Behavioural Guidelines for the Saṅgha'
      parent: Behavioural Guidelines
    2ee43f172b144c0c9ec442f0769cadef:
      title: 'The Seed of Benefit and Happiness: Behavioural Guidelines'
      parent: Behavioural Guidelines
    2f66d835b9c144409930036d9f170b2c:
      title: A Plea to Those who Present ‘Red Offerings’ to Worldly Deities
      parent: Ethical Advice
    ff62894fadca40e49163454119f85b7b:
      title: Nine Considerations and Criteria for Benefiting Beings
      parent: Ethical Advice
created_at: '2022-03-01T03:40:18.761285'
last_modified_at: '2022-03-01T03:40:18.761288'
